apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-python
  template:
    metadata:
      labels:
        app: devops-python
    spec:
      containers:
      - name: devops-python-container
        image: sagarselvi/devops-python-app:latest
        ports:
        - containerPort: 5000
