apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-python-ingress
spec:
  rules:
  - host: devops-python.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-python-service
            port:
              number: 5000
